### ISSUE TITLE
Get rid of register-dns client option

### ISSUE THREAD

**Issue by gesundes** [aovpn/ansible-role-openvpn#13]
If you have register-dns option in the client config it won't work on MacOS (tunnelblick) because it's Windows-only option.

So we need to remove it or replace with something better. Maybe block-outside-dns

**Comment by gesundes** [comment]
It's possible to disable register-dns option from defaults so we did it by default. Probably this issues isn't actual any more.

**Comment by Nmishin** [comment]
agree
