### ISSUE TITLE
Crontab file syntax is wrong for openvpn-crl

### ISSUE THREAD

**Issue by Izual750** [aovpn/ansible-role-openvpn#5]
Hi !

I'm migrating from the Kyl191 openvpn Role, and saw this project might superseed it :eyes: 

When I tried to deploy it, I faced an issue on the task from `server_keys.yml`, the way to configure cron_file seems to contain a typo.
**Error**:
![Screenshot from 2024-07-08 16-16-36](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/efc7a04a-40fb-4f31-8c10-5d40fed62f04)

**Typo**: 
![image](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/a82d3085-605c-41c0-a858-c8d5e48b0031)

**Fix**:
I tried to use [`cron_file`](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/cron_module.html)
![image](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/883d703b-4261-4a28-9e06-292659f0cf30)

**Test**:
-- the task is now working:
![Screenshot from 2024-07-08 16-24-37](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/b40798d5-7d12-4709-a3b4-e4a6bcf2fbd5)

-- And the file created on the server:
![fix](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/3a8375db-154d-4987-a3a2-8557cc03f4e8)

**PR**:
--> https://github.com/aovpn/ansible-role-openvpn/pull/6
( It also contains a few of ansible_lint on the file :) )

**Comment by Izual750** [comment]
Oh it seems i can't find your project in the PR list T_T" 
![image](https://github.com/aovpn/ansible-role-openvpn/assets/11235576/b6619a54-f222-4015-928e-ea751fd6d7fd)

**Comment by Nmishin** [comment]
Yep, this is our idea - to create a community around this Ansible role. :) 
Thank you!

fixed by: https://github.com/aovpn/ansible-role-openvpn/pull/6

**Comment by Izual750** [comment]
Great :D 

I'm using it quite often, so i'll make sure to contribute when possible !

**Comment by Nmishin** [comment]
the same here, but I deployed my openvpn one time and am using this role mostly for user management without deploying new servers ...
